// This file is auto-generated by @hey-api/openapi-ts

export type LegoColorsListData = {
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type LegoColorsListResponse = (unknown);

export type LegoColorsListError = unknown;

export type LegoColorsReadData = {
    path: {
        /**
         * A unique value identifying this color.
         */
        id: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
};

export type LegoColorsReadResponse = (unknown);

export type LegoColorsReadError = unknown;

export type LegoElementsReadData = {
    path: {
        element_id: string;
    };
};

export type LegoElementsReadResponse = (unknown);

export type LegoElementsReadError = unknown;

export type LegoMinifigsListData = {
    query?: {
        in_set_num?: string;
        in_theme_id?: string;
        max_parts?: number;
        min_parts?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
    };
};

export type LegoMinifigsListResponse = (unknown);

export type LegoMinifigsListError = unknown;

export type LegoMinifigsReadData = {
    path: {
        set_num: string;
    };
};

export type LegoMinifigsReadResponse = (unknown);

export type LegoMinifigsReadError = unknown;

export type LegoMinifigsPartsListData = {
    path: {
        set_num: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type LegoMinifigsPartsListResponse = (unknown);

export type LegoMinifigsPartsListError = unknown;

export type LegoMinifigsSetsListData = {
    path: {
        set_num: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type LegoMinifigsSetsListResponse = (unknown);

export type LegoMinifigsSetsListError = unknown;

export type LegoPartCategoriesListData = {
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type LegoPartCategoriesListResponse = (unknown);

export type LegoPartCategoriesListError = unknown;

export type LegoPartCategoriesReadData = {
    path: {
        /**
         * A unique integer value identifying this part category.
         */
        id: number;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
};

export type LegoPartCategoriesReadResponse = (unknown);

export type LegoPartCategoriesReadError = unknown;

export type LegoPartsListData = {
    query?: {
        bricklink_id?: string;
        brickowl_id?: string;
        color_id?: string;
        ldraw_id?: string;
        lego_id?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        part_cat_id?: string;
        part_num?: string;
        part_nums?: string;
        /**
         * A search term.
         */
        search?: string;
    };
};

export type LegoPartsListResponse = (unknown);

export type LegoPartsListError = unknown;

export type LegoPartsReadData = {
    path: {
        part_num: string;
    };
};

export type LegoPartsReadResponse = (unknown);

export type LegoPartsReadError = unknown;

export type LegoPartsColorsListData = {
    path: {
        part_num: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type LegoPartsColorsListResponse = (unknown);

export type LegoPartsColorsListError = unknown;

export type LegoPartsColorsReadData = {
    path: {
        color_id: string;
        part_num: string;
    };
};

export type LegoPartsColorsReadResponse = (unknown);

export type LegoPartsColorsReadError = unknown;

export type LegoPartsColorsSetsListData = {
    path: {
        color_id: string;
        part_num: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type LegoPartsColorsSetsListResponse = (unknown);

export type LegoPartsColorsSetsListError = unknown;

export type LegoSetsListData = {
    query?: {
        max_parts?: number;
        max_year?: number;
        min_parts?: number;
        min_year?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        theme_id?: string;
    };
};

export type LegoSetsListResponse = (unknown);

export type LegoSetsListError = unknown;

export type LegoSetsReadData = {
    path: {
        set_num: string;
    };
};

export type LegoSetsReadResponse = (unknown);

export type LegoSetsReadError = unknown;

export type LegoSetsAlternatesListData = {
    path: {
        set_num: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type LegoSetsAlternatesListResponse = (unknown);

export type LegoSetsAlternatesListError = unknown;

export type LegoSetsMinifigsListData = {
    path: {
        set_num: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type LegoSetsMinifigsListResponse = (unknown);

export type LegoSetsMinifigsListError = unknown;

export type LegoSetsPartsListData = {
    path: {
        set_num: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type LegoSetsPartsListResponse = (unknown);

export type LegoSetsPartsListError = unknown;

export type LegoSetsSetsListData = {
    path: {
        set_num: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type LegoSetsSetsListResponse = (unknown);

export type LegoSetsSetsListError = unknown;

export type LegoThemesListData = {
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type LegoThemesListResponse = (unknown);

export type LegoThemesListError = unknown;

export type LegoThemesReadData = {
    path: {
        /**
         * A unique integer value identifying this theme.
         */
        id: number;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
};

export type LegoThemesReadResponse = (unknown);

export type LegoThemesReadError = unknown;

export type SwaggerListResponse = (unknown);

export type SwaggerListError = unknown;

export type UsersTokenCreateData = unknown;

export type UsersTokenCreateResponse = (unknown);

export type UsersTokenCreateError = unknown;

export type UsersBadgesListData = {
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type UsersBadgesListResponse = (unknown);

export type UsersBadgesListError = unknown;

export type UsersBadgesReadData = {
    path: {
        /**
         * A unique integer value identifying this badge.
         */
        id: number;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
};

export type UsersBadgesReadResponse = (unknown);

export type UsersBadgesReadError = unknown;

export type UsersAllpartsListData = {
    path: {
        user_token: string;
    };
    query?: {
        color_id?: number;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        part_cat_id?: number;
        part_num?: string;
    };
};

export type UsersAllpartsListResponse = (unknown);

export type UsersAllpartsListError = unknown;

export type UsersBuildReadData = {
    path: {
        set_num: string;
        user_token: string;
    };
};

export type UsersBuildReadResponse = (unknown);

export type UsersBuildReadError = unknown;

export type UsersLostPartsListData = {
    path: {
        user_token: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type UsersLostPartsListResponse = (unknown);

export type UsersLostPartsListError = unknown;

export type UsersLostPartsCreateData = {
    path: {
        user_token: string;
    };
};

export type UsersLostPartsCreateResponse = (unknown);

export type UsersLostPartsCreateError = unknown;

export type UsersLostPartsDeleteData = {
    path: {
        id: string;
        user_token: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
};

export type UsersLostPartsDeleteResponse = (void);

export type UsersLostPartsDeleteError = unknown;

export type UsersMinifigsListData = {
    path: {
        user_token: string;
    };
    query?: {
        fig_set_num?: string;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
    };
};

export type UsersMinifigsListResponse = (unknown);

export type UsersMinifigsListError = unknown;

export type UsersPartlistsListData = {
    path: {
        user_token: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type UsersPartlistsListResponse = (unknown);

export type UsersPartlistsListError = unknown;

export type UsersPartlistsCreateData = {
    path: {
        user_token: string;
    };
};

export type UsersPartlistsCreateResponse = (unknown);

export type UsersPartlistsCreateError = unknown;

export type UsersPartlistsReadData = {
    path: {
        list_id: string;
        user_token: string;
    };
};

export type UsersPartlistsReadResponse = (unknown);

export type UsersPartlistsReadError = unknown;

export type UsersPartlistsUpdateData = {
    path: {
        list_id: string;
        user_token: string;
    };
};

export type UsersPartlistsUpdateResponse = (unknown);

export type UsersPartlistsUpdateError = unknown;

export type UsersPartlistsPartialUpdateData = {
    path: {
        list_id: string;
        user_token: string;
    };
};

export type UsersPartlistsPartialUpdateResponse = (unknown);

export type UsersPartlistsPartialUpdateError = unknown;

export type UsersPartlistsDeleteData = {
    path: {
        list_id: string;
        user_token: string;
    };
};

export type UsersPartlistsDeleteResponse = (void);

export type UsersPartlistsDeleteError = unknown;

export type UsersPartlistsPartsListData = {
    path: {
        list_id: string;
        user_token: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type UsersPartlistsPartsListResponse = (unknown);

export type UsersPartlistsPartsListError = unknown;

export type UsersPartlistsPartsCreateData = {
    path: {
        list_id: string;
        user_token: string;
    };
};

export type UsersPartlistsPartsCreateResponse = (unknown);

export type UsersPartlistsPartsCreateError = unknown;

export type UsersPartlistsPartsReadData = {
    path: {
        color_id: string;
        list_id: string;
        part_num: string;
        user_token: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
};

export type UsersPartlistsPartsReadResponse = (unknown);

export type UsersPartlistsPartsReadError = unknown;

export type UsersPartlistsPartsUpdateData = {
    path: {
        color_id: string;
        list_id: string;
        part_num: string;
        user_token: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
};

export type UsersPartlistsPartsUpdateResponse = (unknown);

export type UsersPartlistsPartsUpdateError = unknown;

export type UsersPartlistsPartsDeleteData = {
    path: {
        color_id: string;
        list_id: string;
        part_num: string;
        user_token: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
};

export type UsersPartlistsPartsDeleteResponse = (void);

export type UsersPartlistsPartsDeleteError = unknown;

export type UsersPartsListData = {
    path: {
        user_token: string;
    };
    query?: {
        color_id?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        part_cat_id?: number;
        part_num?: string;
        /**
         * A search term.
         */
        search?: string;
    };
};

export type UsersPartsListResponse = (unknown);

export type UsersPartsListError = unknown;

export type UsersProfileReadData = {
    path: {
        user_token: string;
    };
};

export type UsersProfileReadResponse = (unknown);

export type UsersProfileReadError = unknown;

export type UsersSetlistsListData = {
    path: {
        user_token: string;
    };
    query?: {
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type UsersSetlistsListResponse = (unknown);

export type UsersSetlistsListError = unknown;

export type UsersSetlistsCreateData = {
    path: {
        user_token: string;
    };
};

export type UsersSetlistsCreateResponse = (unknown);

export type UsersSetlistsCreateError = unknown;

export type UsersSetlistsReadData = {
    path: {
        list_id: string;
        user_token: string;
    };
};

export type UsersSetlistsReadResponse = (unknown);

export type UsersSetlistsReadError = unknown;

export type UsersSetlistsUpdateData = {
    path: {
        list_id: string;
        user_token: string;
    };
};

export type UsersSetlistsUpdateResponse = (unknown);

export type UsersSetlistsUpdateError = unknown;

export type UsersSetlistsPartialUpdateData = {
    path: {
        list_id: string;
        user_token: string;
    };
};

export type UsersSetlistsPartialUpdateResponse = (unknown);

export type UsersSetlistsPartialUpdateError = unknown;

export type UsersSetlistsDeleteData = {
    path: {
        list_id: string;
        user_token: string;
    };
};

export type UsersSetlistsDeleteResponse = (void);

export type UsersSetlistsDeleteError = unknown;

export type UsersSetlistsSetsListData = {
    path: {
        list_id: string;
        user_token: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
    };
};

export type UsersSetlistsSetsListResponse = (unknown);

export type UsersSetlistsSetsListError = unknown;

export type UsersSetlistsSetsCreateData = {
    path: {
        list_id: string;
        user_token: string;
    };
};

export type UsersSetlistsSetsCreateResponse = (unknown);

export type UsersSetlistsSetsCreateError = unknown;

export type UsersSetlistsSetsReadData = {
    path: {
        list_id: string;
        set_num: string;
        user_token: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
};

export type UsersSetlistsSetsReadResponse = (unknown);

export type UsersSetlistsSetsReadError = unknown;

export type UsersSetlistsSetsUpdateData = {
    path: {
        list_id: string;
        set_num: string;
        user_token: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
};

export type UsersSetlistsSetsUpdateResponse = (unknown);

export type UsersSetlistsSetsUpdateError = unknown;

export type UsersSetlistsSetsPartialUpdateData = {
    path: {
        list_id: string;
        set_num: string;
        user_token: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
};

export type UsersSetlistsSetsPartialUpdateResponse = (unknown);

export type UsersSetlistsSetsPartialUpdateError = unknown;

export type UsersSetlistsSetsDeleteData = {
    path: {
        list_id: string;
        set_num: string;
        user_token: string;
    };
    query?: {
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
    };
};

export type UsersSetlistsSetsDeleteResponse = (void);

export type UsersSetlistsSetsDeleteError = unknown;

export type UsersSetsListData = {
    path: {
        user_token: string;
    };
    query?: {
        max_parts?: number;
        max_year?: number;
        min_parts?: number;
        min_year?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A page number within the paginated result set.
         */
        page?: number;
        /**
         * Number of results to return per page.
         */
        page_size?: number;
        /**
         * A search term.
         */
        search?: string;
        set_num?: string;
        theme_id?: number;
    };
};

export type UsersSetsListResponse = (unknown);

export type UsersSetsListError = unknown;

export type UsersSetsCreateData = {
    path: {
        user_token: string;
    };
};

export type UsersSetsCreateResponse = (unknown);

export type UsersSetsCreateError = unknown;

export type UsersSetsSyncCreateData = {
    path: {
        user_token: string;
    };
};

export type UsersSetsSyncCreateResponse = (unknown);

export type UsersSetsSyncCreateError = unknown;

export type UsersSetsReadData = {
    path: {
        set_num: string;
        user_token: string;
    };
    query?: {
        max_parts?: number;
        max_year?: number;
        min_parts?: number;
        min_year?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A search term.
         */
        search?: string;
        set_num?: string;
        theme_id?: number;
    };
};

export type UsersSetsReadResponse = (unknown);

export type UsersSetsReadError = unknown;

export type UsersSetsUpdateData = {
    path: {
        set_num: string;
        user_token: string;
    };
    query?: {
        max_parts?: number;
        max_year?: number;
        min_parts?: number;
        min_year?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A search term.
         */
        search?: string;
        set_num?: string;
        theme_id?: number;
    };
};

export type UsersSetsUpdateResponse = (unknown);

export type UsersSetsUpdateError = unknown;

export type UsersSetsDeleteData = {
    path: {
        set_num: string;
        user_token: string;
    };
    query?: {
        max_parts?: number;
        max_year?: number;
        min_parts?: number;
        min_year?: number;
        /**
         * Which field to use when ordering the results.
         */
        ordering?: string;
        /**
         * A search term.
         */
        search?: string;
        set_num?: string;
        theme_id?: number;
    };
};

export type UsersSetsDeleteResponse = (void);

export type UsersSetsDeleteError = unknown;